#ifndef OPENGL_MAIN_H
#define OPENGL_MAIN_H

#include <windows.h>
#include <gl\gl.h>

typedef void (APIENTRY * OPENGL_FUNC_glAccum)(GLenum op, GLfloat value);
typedef void (APIENTRY * OPENGL_FUNC_glAlphaFunc)(GLenum func, GLclampf ref);
typedef GLboolean (APIENTRY * OPENGL_FUNC_glAreTexturesResident)(GLsizei n, const GLuint *textures, GLboolean *residences);
typedef void (APIENTRY * OPENGL_FUNC_glArrayElement)(GLint i);
typedef void (APIENTRY * OPENGL_FUNC_glBegin)(GLenum mode);
typedef void (APIENTRY * OPENGL_FUNC_glBindTexture)(GLenum target, GLuint texture);
typedef void (APIENTRY * OPENGL_FUNC_glBitmap)(GLsizei width, GLsizei height, GLfloat xorig, GLfloat yorig, GLfloat xmove, GLfloat ymove, const GLubyte *bitmap);
typedef void (APIENTRY * OPENGL_FUNC_glBlendFunc)(GLenum sfactor, GLenum dfactor);
typedef void (APIENTRY * OPENGL_FUNC_glCallList)(GLuint list);
typedef void (APIENTRY * OPENGL_FUNC_glCallLists)(GLsizei n, GLenum type, const GLvoid *lists);
typedef void (APIENTRY * OPENGL_FUNC_glClear)(GLbitfield mask);
typedef void (APIENTRY * OPENGL_FUNC_glClearAccum)(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
typedef void (APIENTRY * OPENGL_FUNC_glClearColor)(GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha);
typedef void (APIENTRY * OPENGL_FUNC_glClearDepth)(GLclampd depth);
typedef void (APIENTRY * OPENGL_FUNC_glClearIndex)(GLfloat c);
typedef void (APIENTRY * OPENGL_FUNC_glClearStencil)(GLint s);
typedef void (APIENTRY * OPENGL_FUNC_glClipPlane)(GLenum plane, const GLdouble *equation);
typedef void (APIENTRY * OPENGL_FUNC_glColor3b)(GLbyte red, GLbyte green, GLbyte blue);
typedef void (APIENTRY * OPENGL_FUNC_glColor3bv)(const GLbyte *v);
typedef void (APIENTRY * OPENGL_FUNC_glColor3d)(GLdouble red, GLdouble green, GLdouble blue);
typedef void (APIENTRY * OPENGL_FUNC_glColor3dv)(const GLdouble *v);
typedef void (APIENTRY * OPENGL_FUNC_glColor3f)(GLfloat red, GLfloat green, GLfloat blue);
typedef void (APIENTRY * OPENGL_FUNC_glColor3fv)(const GLfloat *v);
typedef void (APIENTRY * OPENGL_FUNC_glColor3i)(GLint red, GLint green, GLint blue);
typedef void (APIENTRY * OPENGL_FUNC_glColor3iv)(const GLint *v);
typedef void (APIENTRY * OPENGL_FUNC_glColor3s)(GLshort red, GLshort green, GLshort blue);
typedef void (APIENTRY * OPENGL_FUNC_glColor3sv)(const GLshort *v);
typedef void (APIENTRY * OPENGL_FUNC_glColor3ub)(GLubyte red, GLubyte green, GLubyte blue);
typedef void (APIENTRY * OPENGL_FUNC_glColor3ubv)(const GLubyte *v);
typedef void (APIENTRY * OPENGL_FUNC_glColor3ui)(GLuint red, GLuint green, GLuint blue);
typedef void (APIENTRY * OPENGL_FUNC_glColor3uiv)(const GLuint *v);
typedef void (APIENTRY * OPENGL_FUNC_glColor3us)(GLushort red, GLushort green, GLushort blue);
typedef void (APIENTRY * OPENGL_FUNC_glColor3usv)(const GLushort *v);
typedef void (APIENTRY * OPENGL_FUNC_glColor4b)(GLbyte red, GLbyte green, GLbyte blue, GLbyte alpha);
typedef void (APIENTRY * OPENGL_FUNC_glColor4bv)(const GLbyte *v);
typedef void (APIENTRY * OPENGL_FUNC_glColor4d)(GLdouble red, GLdouble green, GLdouble blue, GLdouble alpha);
typedef void (APIENTRY * OPENGL_FUNC_glColor4dv)(const GLdouble *v);
typedef void (APIENTRY * OPENGL_FUNC_glColor4f)(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
typedef void (APIENTRY * OPENGL_FUNC_glColor4fv)(const GLfloat *v);
typedef void (APIENTRY * OPENGL_FUNC_glColor4i)(GLint red, GLint green, GLint blue, GLint alpha);
typedef void (APIENTRY * OPENGL_FUNC_glColor4iv)(const GLint *v);
typedef void (APIENTRY * OPENGL_FUNC_glColor4s)(GLshort red, GLshort green, GLshort blue, GLshort alpha);
typedef void (APIENTRY * OPENGL_FUNC_glColor4sv)(const GLshort *v);
typedef void (APIENTRY * OPENGL_FUNC_glColor4ub)(GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha);
typedef void (APIENTRY * OPENGL_FUNC_glColor4ubv)(const GLubyte *v);
typedef void (APIENTRY * OPENGL_FUNC_glColor4ui)(GLuint red, GLuint green, GLuint blue, GLuint alpha);
typedef void (APIENTRY * OPENGL_FUNC_glColor4uiv)(const GLuint *v);
typedef void (APIENTRY * OPENGL_FUNC_glColor4us)(GLushort red, GLushort green, GLushort blue, GLushort alpha);
typedef void (APIENTRY * OPENGL_FUNC_glColor4usv)(const GLushort *v);
typedef void (APIENTRY * OPENGL_FUNC_glColorMask)(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha);
typedef void (APIENTRY * OPENGL_FUNC_glColorMaterial)(GLenum face, GLenum mode);
typedef void (APIENTRY * OPENGL_FUNC_glColorPointer)(GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
typedef void (APIENTRY * OPENGL_FUNC_glCopyPixels)(GLint x, GLint y, GLsizei width, GLsizei height, GLenum type);
typedef void (APIENTRY * OPENGL_FUNC_glCopyTexImage1D)(GLenum target, GLint level, GLenum internalFormat, GLint x, GLint y, GLsizei width, GLint border);
typedef void (APIENTRY * OPENGL_FUNC_glCopyTexImage2D)(GLenum target, GLint level, GLenum internalFormat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border);
typedef void (APIENTRY * OPENGL_FUNC_glCopyTexSubImage1D)(GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width);
typedef void (APIENTRY * OPENGL_FUNC_glCopyTexSubImage2D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height);
typedef void (APIENTRY * OPENGL_FUNC_glCullFace)(GLenum mode);
typedef void (APIENTRY * OPENGL_FUNC_glDeleteLists)(GLuint list, GLsizei range);
typedef void (APIENTRY * OPENGL_FUNC_glDeleteTextures)(GLsizei n, const GLuint *textures);
typedef void (APIENTRY * OPENGL_FUNC_glDepthFunc)(GLenum func);
typedef void (APIENTRY * OPENGL_FUNC_glDepthMask)(GLboolean flag);
typedef void (APIENTRY * OPENGL_FUNC_glDepthRange)(GLclampd zNear, GLclampd zFar);
typedef void (APIENTRY * OPENGL_FUNC_glDisable)(GLenum cap);
typedef void (APIENTRY * OPENGL_FUNC_glDisableClientState)(GLenum array);
typedef void (APIENTRY * OPENGL_FUNC_glDrawArrays)(GLenum mode, GLint first, GLsizei count);
typedef void (APIENTRY * OPENGL_FUNC_glDrawBuffer)(GLenum mode);
typedef void (APIENTRY * OPENGL_FUNC_glDrawElements)(GLenum mode, GLsizei count, GLenum type, const GLvoid *indices);
typedef void (APIENTRY * OPENGL_FUNC_glDrawPixels)(GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels);
typedef void (APIENTRY * OPENGL_FUNC_glEdgeFlag)(GLboolean flag);
typedef void (APIENTRY * OPENGL_FUNC_glEdgeFlagPointer)(GLsizei stride, const GLvoid *pointer);
typedef void (APIENTRY * OPENGL_FUNC_glEdgeFlagv)(const GLboolean *flag);
typedef void (APIENTRY * OPENGL_FUNC_glEnable)(GLenum cap);
typedef void (APIENTRY * OPENGL_FUNC_glEnableClientState)(GLenum array);
typedef void (APIENTRY * OPENGL_FUNC_glEnd)(void);
typedef void (APIENTRY * OPENGL_FUNC_glEndList)(void);
typedef void (APIENTRY * OPENGL_FUNC_glEvalCoord1d)(GLdouble u);
typedef void (APIENTRY * OPENGL_FUNC_glEvalCoord1dv)(const GLdouble *u);
typedef void (APIENTRY * OPENGL_FUNC_glEvalCoord1f)(GLfloat u);
typedef void (APIENTRY * OPENGL_FUNC_glEvalCoord1fv)(const GLfloat *u);
typedef void (APIENTRY * OPENGL_FUNC_glEvalCoord2d)(GLdouble u, GLdouble v);
typedef void (APIENTRY * OPENGL_FUNC_glEvalCoord2dv)(const GLdouble *u);
typedef void (APIENTRY * OPENGL_FUNC_glEvalCoord2f)(GLfloat u, GLfloat v);
typedef void (APIENTRY * OPENGL_FUNC_glEvalCoord2fv)(const GLfloat *u);
typedef void (APIENTRY * OPENGL_FUNC_glEvalMesh1)(GLenum mode, GLint i1, GLint i2);
typedef void (APIENTRY * OPENGL_FUNC_glEvalMesh2)(GLenum mode, GLint i1, GLint i2, GLint j1, GLint j2);
typedef void (APIENTRY * OPENGL_FUNC_glEvalPoint1)(GLint i);
typedef void (APIENTRY * OPENGL_FUNC_glEvalPoint2)(GLint i, GLint j);
typedef void (APIENTRY * OPENGL_FUNC_glFeedbackBuffer)(GLsizei size, GLenum type, GLfloat *buffer);
typedef void (APIENTRY * OPENGL_FUNC_glFinish)(void);
typedef void (APIENTRY * OPENGL_FUNC_glFlush)(void);
typedef void (APIENTRY * OPENGL_FUNC_glFogf)(GLenum pname, GLfloat param);
typedef void (APIENTRY * OPENGL_FUNC_glFogfv)(GLenum pname, const GLfloat *params);
typedef void (APIENTRY * OPENGL_FUNC_glFogi)(GLenum pname, GLint param);
typedef void (APIENTRY * OPENGL_FUNC_glFogiv)(GLenum pname, const GLint *params);
typedef void (APIENTRY * OPENGL_FUNC_glFrontFace)(GLenum mode);
typedef void (APIENTRY * OPENGL_FUNC_glFrustum)(GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar);
typedef GLuint (APIENTRY * OPENGL_FUNC_glGenLists)(GLsizei range);
typedef void (APIENTRY * OPENGL_FUNC_glGenTextures)(GLsizei n, GLuint *textures);
typedef void (APIENTRY * OPENGL_FUNC_glGetBooleanv)(GLenum pname, GLboolean *params);
typedef void (APIENTRY * OPENGL_FUNC_glGetClipPlane)(GLenum plane, GLdouble *equation);
typedef void (APIENTRY * OPENGL_FUNC_glGetDoublev)(GLenum pname, GLdouble *params);
typedef GLenum (APIENTRY * OPENGL_FUNC_glGetError)(void);
typedef void (APIENTRY * OPENGL_FUNC_glGetFloatv)(GLenum pname, GLfloat *params);
typedef void (APIENTRY * OPENGL_FUNC_glGetIntegerv)(GLenum pname, GLint *params);
typedef void (APIENTRY * OPENGL_FUNC_glGetLightfv)(GLenum light, GLenum pname, GLfloat *params);
typedef void (APIENTRY * OPENGL_FUNC_glGetLightiv)(GLenum light, GLenum pname, GLint *params);
typedef void (APIENTRY * OPENGL_FUNC_glGetMapdv)(GLenum target, GLenum query, GLdouble *v);
typedef void (APIENTRY * OPENGL_FUNC_glGetMapfv)(GLenum target, GLenum query, GLfloat *v);
typedef void (APIENTRY * OPENGL_FUNC_glGetMapiv)(GLenum target, GLenum query, GLint *v);
typedef void (APIENTRY * OPENGL_FUNC_glGetMaterialfv)(GLenum face, GLenum pname, GLfloat *params);
typedef void (APIENTRY * OPENGL_FUNC_glGetMaterialiv)(GLenum face, GLenum pname, GLint *params);
typedef void (APIENTRY * OPENGL_FUNC_glGetPixelMapfv)(GLenum map, GLfloat *values);
typedef void (APIENTRY * OPENGL_FUNC_glGetPixelMapuiv)(GLenum map, GLuint *values);
typedef void (APIENTRY * OPENGL_FUNC_glGetPixelMapusv)(GLenum map, GLushort *values);
typedef void (APIENTRY * OPENGL_FUNC_glGetPointerv)(GLenum pname, GLvoid* *params);
typedef void (APIENTRY * OPENGL_FUNC_glGetPolygonStipple)(GLubyte *mask);
typedef const GLubyte * (APIENTRY * OPENGL_FUNC_glGetString)(GLenum name);
typedef void (APIENTRY * OPENGL_FUNC_glGetTexEnvfv)(GLenum target, GLenum pname, GLfloat *params);
typedef void (APIENTRY * OPENGL_FUNC_glGetTexEnviv)(GLenum target, GLenum pname, GLint *params);
typedef void (APIENTRY * OPENGL_FUNC_glGetTexGendv)(GLenum coord, GLenum pname, GLdouble *params);
typedef void (APIENTRY * OPENGL_FUNC_glGetTexGenfv)(GLenum coord, GLenum pname, GLfloat *params);
typedef void (APIENTRY * OPENGL_FUNC_glGetTexGeniv)(GLenum coord, GLenum pname, GLint *params);
typedef void (APIENTRY * OPENGL_FUNC_glGetTexImage)(GLenum target, GLint level, GLenum format, GLenum type, GLvoid *pixels);
typedef void (APIENTRY * OPENGL_FUNC_glGetTexLevelParameterfv)(GLenum target, GLint level, GLenum pname, GLfloat *params);
typedef void (APIENTRY * OPENGL_FUNC_glGetTexLevelParameteriv)(GLenum target, GLint level, GLenum pname, GLint *params);
typedef void (APIENTRY * OPENGL_FUNC_glGetTexParameterfv)(GLenum target, GLenum pname, GLfloat *params);
typedef void (APIENTRY * OPENGL_FUNC_glGetTexParameteriv)(GLenum target, GLenum pname, GLint *params);
typedef void (APIENTRY * OPENGL_FUNC_glHint)(GLenum target, GLenum mode);
typedef void (APIENTRY * OPENGL_FUNC_glIndexMask)(GLuint mask);
typedef void (APIENTRY * OPENGL_FUNC_glIndexPointer)(GLenum type, GLsizei stride, const GLvoid *pointer);
typedef void (APIENTRY * OPENGL_FUNC_glIndexd)(GLdouble c);
typedef void (APIENTRY * OPENGL_FUNC_glIndexdv)(const GLdouble *c);
typedef void (APIENTRY * OPENGL_FUNC_glIndexf)(GLfloat c);
typedef void (APIENTRY * OPENGL_FUNC_glIndexfv)(const GLfloat *c);
typedef void (APIENTRY * OPENGL_FUNC_glIndexi)(GLint c);
typedef void (APIENTRY * OPENGL_FUNC_glIndexiv)(const GLint *c);
typedef void (APIENTRY * OPENGL_FUNC_glIndexs)(GLshort c);
typedef void (APIENTRY * OPENGL_FUNC_glIndexsv)(const GLshort *c);
typedef void (APIENTRY * OPENGL_FUNC_glIndexub)(GLubyte c);
typedef void (APIENTRY * OPENGL_FUNC_glIndexubv)(const GLubyte *c);
typedef void (APIENTRY * OPENGL_FUNC_glInitNames)(void);
typedef void (APIENTRY * OPENGL_FUNC_glInterleavedArrays)(GLenum format, GLsizei stride, const GLvoid *pointer);
typedef GLboolean (APIENTRY * OPENGL_FUNC_glIsEnabled)(GLenum cap);
typedef GLboolean (APIENTRY * OPENGL_FUNC_glIsList)(GLuint list);
typedef GLboolean (APIENTRY * OPENGL_FUNC_glIsTexture)(GLuint texture);
typedef void (APIENTRY * OPENGL_FUNC_glLightModelf)(GLenum pname, GLfloat param);
typedef void (APIENTRY * OPENGL_FUNC_glLightModelfv)(GLenum pname, const GLfloat *params);
typedef void (APIENTRY * OPENGL_FUNC_glLightModeli)(GLenum pname, GLint param);
typedef void (APIENTRY * OPENGL_FUNC_glLightModeliv)(GLenum pname, const GLint *params);
typedef void (APIENTRY * OPENGL_FUNC_glLightf)(GLenum light, GLenum pname, GLfloat param);
typedef void (APIENTRY * OPENGL_FUNC_glLightfv)(GLenum light, GLenum pname, const GLfloat *params);
typedef void (APIENTRY * OPENGL_FUNC_glLighti)(GLenum light, GLenum pname, GLint param);
typedef void (APIENTRY * OPENGL_FUNC_glLightiv)(GLenum light, GLenum pname, const GLint *params);
typedef void (APIENTRY * OPENGL_FUNC_glLineStipple)(GLint factor, GLushort pattern);
typedef void (APIENTRY * OPENGL_FUNC_glLineWidth)(GLfloat width);
typedef void (APIENTRY * OPENGL_FUNC_glListBase)(GLuint base);
typedef void (APIENTRY * OPENGL_FUNC_glLoadIdentity)(void);
typedef void (APIENTRY * OPENGL_FUNC_glLoadMatrixd)(const GLdouble *m);
typedef void (APIENTRY * OPENGL_FUNC_glLoadMatrixf)(const GLfloat *m);
typedef void (APIENTRY * OPENGL_FUNC_glLoadName)(GLuint name);
typedef void (APIENTRY * OPENGL_FUNC_glLogicOp)(GLenum opcode);
typedef void (APIENTRY * OPENGL_FUNC_glMap1d)(GLenum target, GLdouble u1, GLdouble u2, GLint stride, GLint order, const GLdouble *points);
typedef void (APIENTRY * OPENGL_FUNC_glMap1f)(GLenum target, GLfloat u1, GLfloat u2, GLint stride, GLint order, const GLfloat *points);
typedef void (APIENTRY * OPENGL_FUNC_glMap2d)(GLenum target, GLdouble u1, GLdouble u2, GLint ustride, GLint uorder, GLdouble v1, GLdouble v2, GLint vstride, GLint vorder, const GLdouble *points);
typedef void (APIENTRY * OPENGL_FUNC_glMap2f)(GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, GLfloat v1, GLfloat v2, GLint vstride, GLint vorder, const GLfloat *points);
typedef void (APIENTRY * OPENGL_FUNC_glMapGrid1d)(GLint un, GLdouble u1, GLdouble u2);
typedef void (APIENTRY * OPENGL_FUNC_glMapGrid1f)(GLint un, GLfloat u1, GLfloat u2);
typedef void (APIENTRY * OPENGL_FUNC_glMapGrid2d)(GLint un, GLdouble u1, GLdouble u2, GLint vn, GLdouble v1, GLdouble v2);
typedef void (APIENTRY * OPENGL_FUNC_glMapGrid2f)(GLint un, GLfloat u1, GLfloat u2, GLint vn, GLfloat v1, GLfloat v2);
typedef void (APIENTRY * OPENGL_FUNC_glMaterialf)(GLenum face, GLenum pname, GLfloat param);
typedef void (APIENTRY * OPENGL_FUNC_glMaterialfv)(GLenum face, GLenum pname, const GLfloat *params);
typedef void (APIENTRY * OPENGL_FUNC_glMateriali)(GLenum face, GLenum pname, GLint param);
typedef void (APIENTRY * OPENGL_FUNC_glMaterialiv)(GLenum face, GLenum pname, const GLint *params);
typedef void (APIENTRY * OPENGL_FUNC_glMatrixMode)(GLenum mode);
typedef void (APIENTRY * OPENGL_FUNC_glMultMatrixd)(const GLdouble *m);
typedef void (APIENTRY * OPENGL_FUNC_glMultMatrixf)(const GLfloat *m);
typedef void (APIENTRY * OPENGL_FUNC_glNewList)(GLuint list, GLenum mode);
typedef void (APIENTRY * OPENGL_FUNC_glNormal3b)(GLbyte nx, GLbyte ny, GLbyte nz);
typedef void (APIENTRY * OPENGL_FUNC_glNormal3bv)(const GLbyte *v);
typedef void (APIENTRY * OPENGL_FUNC_glNormal3d)(GLdouble nx, GLdouble ny, GLdouble nz);
typedef void (APIENTRY * OPENGL_FUNC_glNormal3dv)(const GLdouble *v);
typedef void (APIENTRY * OPENGL_FUNC_glNormal3f)(GLfloat nx, GLfloat ny, GLfloat nz);
typedef void (APIENTRY * OPENGL_FUNC_glNormal3fv)(const GLfloat *v);
typedef void (APIENTRY * OPENGL_FUNC_glNormal3i)(GLint nx, GLint ny, GLint nz);
typedef void (APIENTRY * OPENGL_FUNC_glNormal3iv)(const GLint *v);
typedef void (APIENTRY * OPENGL_FUNC_glNormal3s)(GLshort nx, GLshort ny, GLshort nz);
typedef void (APIENTRY * OPENGL_FUNC_glNormal3sv)(const GLshort *v);
typedef void (APIENTRY * OPENGL_FUNC_glNormalPointer)(GLenum type, GLsizei stride, const GLvoid *pointer);
typedef void (APIENTRY * OPENGL_FUNC_glOrtho)(GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar);
typedef void (APIENTRY * OPENGL_FUNC_glPassThrough)(GLfloat token);
typedef void (APIENTRY * OPENGL_FUNC_glPixelMapfv)(GLenum map, GLsizei mapsize, const GLfloat *values);
typedef void (APIENTRY * OPENGL_FUNC_glPixelMapuiv)(GLenum map, GLsizei mapsize, const GLuint *values);
typedef void (APIENTRY * OPENGL_FUNC_glPixelMapusv)(GLenum map, GLsizei mapsize, const GLushort *values);
typedef void (APIENTRY * OPENGL_FUNC_glPixelStoref)(GLenum pname, GLfloat param);
typedef void (APIENTRY * OPENGL_FUNC_glPixelStorei)(GLenum pname, GLint param);
typedef void (APIENTRY * OPENGL_FUNC_glPixelTransferf)(GLenum pname, GLfloat param);
typedef void (APIENTRY * OPENGL_FUNC_glPixelTransferi)(GLenum pname, GLint param);
typedef void (APIENTRY * OPENGL_FUNC_glPixelZoom)(GLfloat xfactor, GLfloat yfactor);
typedef void (APIENTRY * OPENGL_FUNC_glPointSize)(GLfloat size);
typedef void (APIENTRY * OPENGL_FUNC_glPolygonMode)(GLenum face, GLenum mode);
typedef void (APIENTRY * OPENGL_FUNC_glPolygonOffset)(GLfloat factor, GLfloat units);
typedef void (APIENTRY * OPENGL_FUNC_glPolygonStipple)(const GLubyte *mask);
typedef void (APIENTRY * OPENGL_FUNC_glPopAttrib)(void);
typedef void (APIENTRY * OPENGL_FUNC_glPopClientAttrib)(void);
typedef void (APIENTRY * OPENGL_FUNC_glPopMatrix)(void);
typedef void (APIENTRY * OPENGL_FUNC_glPopName)(void);
typedef void (APIENTRY * OPENGL_FUNC_glPrioritizeTextures)(GLsizei n, const GLuint *textures, const GLclampf *priorities);
typedef void (APIENTRY * OPENGL_FUNC_glPushAttrib)(GLbitfield mask);
typedef void (APIENTRY * OPENGL_FUNC_glPushClientAttrib)(GLbitfield mask);
typedef void (APIENTRY * OPENGL_FUNC_glPushMatrix)(void);
typedef void (APIENTRY * OPENGL_FUNC_glPushName)(GLuint name);
typedef void (APIENTRY * OPENGL_FUNC_glRasterPos2d)(GLdouble x, GLdouble y);
typedef void (APIENTRY * OPENGL_FUNC_glRasterPos2dv)(const GLdouble *v);
typedef void (APIENTRY * OPENGL_FUNC_glRasterPos2f)(GLfloat x, GLfloat y);
typedef void (APIENTRY * OPENGL_FUNC_glRasterPos2fv)(const GLfloat *v);
typedef void (APIENTRY * OPENGL_FUNC_glRasterPos2i)(GLint x, GLint y);
typedef void (APIENTRY * OPENGL_FUNC_glRasterPos2iv)(const GLint *v);
typedef void (APIENTRY * OPENGL_FUNC_glRasterPos2s)(GLshort x, GLshort y);
typedef void (APIENTRY * OPENGL_FUNC_glRasterPos2sv)(const GLshort *v);
typedef void (APIENTRY * OPENGL_FUNC_glRasterPos3d)(GLdouble x, GLdouble y, GLdouble z);
typedef void (APIENTRY * OPENGL_FUNC_glRasterPos3dv)(const GLdouble *v);
typedef void (APIENTRY * OPENGL_FUNC_glRasterPos3f)(GLfloat x, GLfloat y, GLfloat z);
typedef void (APIENTRY * OPENGL_FUNC_glRasterPos3fv)(const GLfloat *v);
typedef void (APIENTRY * OPENGL_FUNC_glRasterPos3i)(GLint x, GLint y, GLint z);
typedef void (APIENTRY * OPENGL_FUNC_glRasterPos3iv)(const GLint *v);
typedef void (APIENTRY * OPENGL_FUNC_glRasterPos3s)(GLshort x, GLshort y, GLshort z);
typedef void (APIENTRY * OPENGL_FUNC_glRasterPos3sv)(const GLshort *v);
typedef void (APIENTRY * OPENGL_FUNC_glRasterPos4d)(GLdouble x, GLdouble y, GLdouble z, GLdouble w);
typedef void (APIENTRY * OPENGL_FUNC_glRasterPos4dv)(const GLdouble *v);
typedef void (APIENTRY * OPENGL_FUNC_glRasterPos4f)(GLfloat x, GLfloat y, GLfloat z, GLfloat w);
typedef void (APIENTRY * OPENGL_FUNC_glRasterPos4fv)(const GLfloat *v);
typedef void (APIENTRY * OPENGL_FUNC_glRasterPos4i)(GLint x, GLint y, GLint z, GLint w);
typedef void (APIENTRY * OPENGL_FUNC_glRasterPos4iv)(const GLint *v);
typedef void (APIENTRY * OPENGL_FUNC_glRasterPos4s)(GLshort x, GLshort y, GLshort z, GLshort w);
typedef void (APIENTRY * OPENGL_FUNC_glRasterPos4sv)(const GLshort *v);
typedef void (APIENTRY * OPENGL_FUNC_glReadBuffer)(GLenum mode);
typedef void (APIENTRY * OPENGL_FUNC_glReadPixels)(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels);
typedef void (APIENTRY * OPENGL_FUNC_glRectd)(GLdouble x1, GLdouble y1, GLdouble x2, GLdouble y2);
typedef void (APIENTRY * OPENGL_FUNC_glRectdv)(const GLdouble *v1, const GLdouble *v2);
typedef void (APIENTRY * OPENGL_FUNC_glRectf)(GLfloat x1, GLfloat y1, GLfloat x2, GLfloat y2);
typedef void (APIENTRY * OPENGL_FUNC_glRectfv)(const GLfloat *v1, const GLfloat *v2);
typedef void (APIENTRY * OPENGL_FUNC_glRecti)(GLint x1, GLint y1, GLint x2, GLint y2);
typedef void (APIENTRY * OPENGL_FUNC_glRectiv)(const GLint *v1, const GLint *v2);
typedef void (APIENTRY * OPENGL_FUNC_glRects)(GLshort x1, GLshort y1, GLshort x2, GLshort y2);
typedef void (APIENTRY * OPENGL_FUNC_glRectsv)(const GLshort *v1, const GLshort *v2);
typedef GLint (APIENTRY * OPENGL_FUNC_glRenderMode)(GLenum mode);
typedef void (APIENTRY * OPENGL_FUNC_glRotated)(GLdouble angle, GLdouble x, GLdouble y, GLdouble z);
typedef void (APIENTRY * OPENGL_FUNC_glRotatef)(GLfloat angle, GLfloat x, GLfloat y, GLfloat z);
typedef void (APIENTRY * OPENGL_FUNC_glScaled)(GLdouble x, GLdouble y, GLdouble z);
typedef void (APIENTRY * OPENGL_FUNC_glScalef)(GLfloat x, GLfloat y, GLfloat z);
typedef void (APIENTRY * OPENGL_FUNC_glScissor)(GLint x, GLint y, GLsizei width, GLsizei height);
typedef void (APIENTRY * OPENGL_FUNC_glSelectBuffer)(GLsizei size, GLuint *buffer);
typedef void (APIENTRY * OPENGL_FUNC_glShadeModel)(GLenum mode);
typedef void (APIENTRY * OPENGL_FUNC_glStencilFunc)(GLenum func, GLint ref, GLuint mask);
typedef void (APIENTRY * OPENGL_FUNC_glStencilMask)(GLuint mask);
typedef void (APIENTRY * OPENGL_FUNC_glStencilOp)(GLenum fail, GLenum zfail, GLenum zpass);
typedef void (APIENTRY * OPENGL_FUNC_glTexCoord1d)(GLdouble s);
typedef void (APIENTRY * OPENGL_FUNC_glTexCoord1dv)(const GLdouble *v);
typedef void (APIENTRY * OPENGL_FUNC_glTexCoord1f)(GLfloat s);
typedef void (APIENTRY * OPENGL_FUNC_glTexCoord1fv)(const GLfloat *v);
typedef void (APIENTRY * OPENGL_FUNC_glTexCoord1i)(GLint s);
typedef void (APIENTRY * OPENGL_FUNC_glTexCoord1iv)(const GLint *v);
typedef void (APIENTRY * OPENGL_FUNC_glTexCoord1s)(GLshort s);
typedef void (APIENTRY * OPENGL_FUNC_glTexCoord1sv)(const GLshort *v);
typedef void (APIENTRY * OPENGL_FUNC_glTexCoord2d)(GLdouble s, GLdouble t);
typedef void (APIENTRY * OPENGL_FUNC_glTexCoord2dv)(const GLdouble *v);
typedef void (APIENTRY * OPENGL_FUNC_glTexCoord2f)(GLfloat s, GLfloat t);
typedef void (APIENTRY * OPENGL_FUNC_glTexCoord2fv)(const GLfloat *v);
typedef void (APIENTRY * OPENGL_FUNC_glTexCoord2i)(GLint s, GLint t);
typedef void (APIENTRY * OPENGL_FUNC_glTexCoord2iv)(const GLint *v);
typedef void (APIENTRY * OPENGL_FUNC_glTexCoord2s)(GLshort s, GLshort t);
typedef void (APIENTRY * OPENGL_FUNC_glTexCoord2sv)(const GLshort *v);
typedef void (APIENTRY * OPENGL_FUNC_glTexCoord3d)(GLdouble s, GLdouble t, GLdouble r);
typedef void (APIENTRY * OPENGL_FUNC_glTexCoord3dv)(const GLdouble *v);
typedef void (APIENTRY * OPENGL_FUNC_glTexCoord3f)(GLfloat s, GLfloat t, GLfloat r);
typedef void (APIENTRY * OPENGL_FUNC_glTexCoord3fv)(const GLfloat *v);
typedef void (APIENTRY * OPENGL_FUNC_glTexCoord3i)(GLint s, GLint t, GLint r);
typedef void (APIENTRY * OPENGL_FUNC_glTexCoord3iv)(const GLint *v);
typedef void (APIENTRY * OPENGL_FUNC_glTexCoord3s)(GLshort s, GLshort t, GLshort r);
typedef void (APIENTRY * OPENGL_FUNC_glTexCoord3sv)(const GLshort *v);
typedef void (APIENTRY * OPENGL_FUNC_glTexCoord4d)(GLdouble s, GLdouble t, GLdouble r, GLdouble q);
typedef void (APIENTRY * OPENGL_FUNC_glTexCoord4dv)(const GLdouble *v);
typedef void (APIENTRY * OPENGL_FUNC_glTexCoord4f)(GLfloat s, GLfloat t, GLfloat r, GLfloat q);
typedef void (APIENTRY * OPENGL_FUNC_glTexCoord4fv)(const GLfloat *v);
typedef void (APIENTRY * OPENGL_FUNC_glTexCoord4i)(GLint s, GLint t, GLint r, GLint q);
typedef void (APIENTRY * OPENGL_FUNC_glTexCoord4iv)(const GLint *v);
typedef void (APIENTRY * OPENGL_FUNC_glTexCoord4s)(GLshort s, GLshort t, GLshort r, GLshort q);
typedef void (APIENTRY * OPENGL_FUNC_glTexCoord4sv)(const GLshort *v);
typedef void (APIENTRY * OPENGL_FUNC_glTexCoordPointer)(GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
typedef void (APIENTRY * OPENGL_FUNC_glTexEnvf)(GLenum target, GLenum pname, GLfloat param);
typedef void (APIENTRY * OPENGL_FUNC_glTexEnvfv)(GLenum target, GLenum pname, const GLfloat *params);
typedef void (APIENTRY * OPENGL_FUNC_glTexEnvi)(GLenum target, GLenum pname, GLint param);
typedef void (APIENTRY * OPENGL_FUNC_glTexEnviv)(GLenum target, GLenum pname, const GLint *params);
typedef void (APIENTRY * OPENGL_FUNC_glTexGend)(GLenum coord, GLenum pname, GLdouble param);
typedef void (APIENTRY * OPENGL_FUNC_glTexGendv)(GLenum coord, GLenum pname, const GLdouble *params);
typedef void (APIENTRY * OPENGL_FUNC_glTexGenf)(GLenum coord, GLenum pname, GLfloat param);
typedef void (APIENTRY * OPENGL_FUNC_glTexGenfv)(GLenum coord, GLenum pname, const GLfloat *params);
typedef void (APIENTRY * OPENGL_FUNC_glTexGeni)(GLenum coord, GLenum pname, GLint param);
typedef void (APIENTRY * OPENGL_FUNC_glTexGeniv)(GLenum coord, GLenum pname, const GLint *params);
typedef void (APIENTRY * OPENGL_FUNC_glTexImage1D)(GLenum target, GLint level, GLint internalformat, GLsizei width, GLint border, GLenum format, GLenum type, const GLvoid *pixels);
typedef void (APIENTRY * OPENGL_FUNC_glTexImage2D)(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid *pixels);
typedef void (APIENTRY * OPENGL_FUNC_glTexParameterf)(GLenum target, GLenum pname, GLfloat param);
typedef void (APIENTRY * OPENGL_FUNC_glTexParameterfv)(GLenum target, GLenum pname, const GLfloat *params);
typedef void (APIENTRY * OPENGL_FUNC_glTexParameteri)(GLenum target, GLenum pname, GLint param);
typedef void (APIENTRY * OPENGL_FUNC_glTexParameteriv)(GLenum target, GLenum pname, const GLint *params);
typedef void (APIENTRY * OPENGL_FUNC_glTexSubImage1D)(GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const GLvoid *pixels);
typedef void (APIENTRY * OPENGL_FUNC_glTexSubImage2D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels);
typedef void (APIENTRY * OPENGL_FUNC_glTranslated)(GLdouble x, GLdouble y, GLdouble z);
typedef void (APIENTRY * OPENGL_FUNC_glTranslatef)(GLfloat x, GLfloat y, GLfloat z);
typedef void (APIENTRY * OPENGL_FUNC_glVertex2d)(GLdouble x, GLdouble y);
typedef void (APIENTRY * OPENGL_FUNC_glVertex2dv)(const GLdouble *v);
typedef void (APIENTRY * OPENGL_FUNC_glVertex2f)(GLfloat x, GLfloat y);
typedef void (APIENTRY * OPENGL_FUNC_glVertex2fv)(const GLfloat *v);
typedef void (APIENTRY * OPENGL_FUNC_glVertex2i)(GLint x, GLint y);
typedef void (APIENTRY * OPENGL_FUNC_glVertex2iv)(const GLint *v);
typedef void (APIENTRY * OPENGL_FUNC_glVertex2s)(GLshort x, GLshort y);
typedef void (APIENTRY * OPENGL_FUNC_glVertex2sv)(const GLshort *v);
typedef void (APIENTRY * OPENGL_FUNC_glVertex3d)(GLdouble x, GLdouble y, GLdouble z);
typedef void (APIENTRY * OPENGL_FUNC_glVertex3dv)(const GLdouble *v);
typedef void (APIENTRY * OPENGL_FUNC_glVertex3f)(GLfloat x, GLfloat y, GLfloat z);
typedef void (APIENTRY * OPENGL_FUNC_glVertex3fv)(const GLfloat *v);
typedef void (APIENTRY * OPENGL_FUNC_glVertex3i)(GLint x, GLint y, GLint z);
typedef void (APIENTRY * OPENGL_FUNC_glVertex3iv)(const GLint *v);
typedef void (APIENTRY * OPENGL_FUNC_glVertex3s)(GLshort x, GLshort y, GLshort z);
typedef void (APIENTRY * OPENGL_FUNC_glVertex3sv)(const GLshort *v);
typedef void (APIENTRY * OPENGL_FUNC_glVertex4d)(GLdouble x, GLdouble y, GLdouble z, GLdouble w);
typedef void (APIENTRY * OPENGL_FUNC_glVertex4dv)(const GLdouble *v);
typedef void (APIENTRY * OPENGL_FUNC_glVertex4f)(GLfloat x, GLfloat y, GLfloat z, GLfloat w);
typedef void (APIENTRY * OPENGL_FUNC_glVertex4fv)(const GLfloat *v);
typedef void (APIENTRY * OPENGL_FUNC_glVertex4i)(GLint x, GLint y, GLint z, GLint w);
typedef void (APIENTRY * OPENGL_FUNC_glVertex4iv)(const GLint *v);
typedef void (APIENTRY * OPENGL_FUNC_glVertex4s)(GLshort x, GLshort y, GLshort z, GLshort w);
typedef void (APIENTRY * OPENGL_FUNC_glVertex4sv)(const GLshort *v);
typedef void (APIENTRY * OPENGL_FUNC_glVertexPointer)(GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
typedef void (APIENTRY * OPENGL_FUNC_glViewport)(GLint x, GLint y, GLsizei width, GLsizei height);

struct OPENGL_CONTEXT
{
	OPENGL_FUNC_glAccum glAccum;
	OPENGL_FUNC_glAlphaFunc glAlphaFunc;
	OPENGL_FUNC_glAreTexturesResident glAreTexturesResident;
	OPENGL_FUNC_glArrayElement glArrayElement;
	OPENGL_FUNC_glBegin glBegin;
	OPENGL_FUNC_glBindTexture glBindTexture;
	OPENGL_FUNC_glBitmap glBitmap;
	OPENGL_FUNC_glBlendFunc glBlendFunc;
	OPENGL_FUNC_glCallList glCallList;
	OPENGL_FUNC_glCallLists glCallLists;
	OPENGL_FUNC_glClear glClear;
	OPENGL_FUNC_glClearAccum glClearAccum;
	OPENGL_FUNC_glClearColor glClearColor;
	OPENGL_FUNC_glClearDepth glClearDepth;
	OPENGL_FUNC_glClearIndex glClearIndex;
	OPENGL_FUNC_glClearStencil glClearStencil;
	OPENGL_FUNC_glClipPlane glClipPlane;
	OPENGL_FUNC_glColor3b glColor3b;
	OPENGL_FUNC_glColor3bv glColor3bv;
	OPENGL_FUNC_glColor3d glColor3d;
	OPENGL_FUNC_glColor3dv glColor3dv;
	OPENGL_FUNC_glColor3f glColor3f;
	OPENGL_FUNC_glColor3fv glColor3fv;
	OPENGL_FUNC_glColor3i glColor3i;
	OPENGL_FUNC_glColor3iv glColor3iv;
	OPENGL_FUNC_glColor3s glColor3s;
	OPENGL_FUNC_glColor3sv glColor3sv;
	OPENGL_FUNC_glColor3ub glColor3ub;
	OPENGL_FUNC_glColor3ubv glColor3ubv;
	OPENGL_FUNC_glColor3ui glColor3ui;
	OPENGL_FUNC_glColor3uiv glColor3uiv;
	OPENGL_FUNC_glColor3us glColor3us;
	OPENGL_FUNC_glColor3usv glColor3usv;
	OPENGL_FUNC_glColor4b glColor4b;
	OPENGL_FUNC_glColor4bv glColor4bv;
	OPENGL_FUNC_glColor4d glColor4d;
	OPENGL_FUNC_glColor4dv glColor4dv;
	OPENGL_FUNC_glColor4f glColor4f;
	OPENGL_FUNC_glColor4fv glColor4fv;
	OPENGL_FUNC_glColor4i glColor4i;
	OPENGL_FUNC_glColor4iv glColor4iv;
	OPENGL_FUNC_glColor4s glColor4s;
	OPENGL_FUNC_glColor4sv glColor4sv;
	OPENGL_FUNC_glColor4ub glColor4ub;
	OPENGL_FUNC_glColor4ubv glColor4ubv;
	OPENGL_FUNC_glColor4ui glColor4ui;
	OPENGL_FUNC_glColor4uiv glColor4uiv;
	OPENGL_FUNC_glColor4us glColor4us;
	OPENGL_FUNC_glColor4usv glColor4usv;
	OPENGL_FUNC_glColorMask glColorMask;
	OPENGL_FUNC_glColorMaterial glColorMaterial;
	OPENGL_FUNC_glColorPointer glColorPointer;
	OPENGL_FUNC_glCopyPixels glCopyPixels;
	OPENGL_FUNC_glCopyTexImage1D glCopyTexImage1D;
	OPENGL_FUNC_glCopyTexImage2D glCopyTexImage2D;
	OPENGL_FUNC_glCopyTexSubImage1D glCopyTexSubImage1D;
	OPENGL_FUNC_glCopyTexSubImage2D glCopyTexSubImage2D;
	OPENGL_FUNC_glCullFace glCullFace;
	OPENGL_FUNC_glDeleteLists glDeleteLists;
	OPENGL_FUNC_glDeleteTextures glDeleteTextures;
	OPENGL_FUNC_glDepthFunc glDepthFunc;
	OPENGL_FUNC_glDepthMask glDepthMask;
	OPENGL_FUNC_glDepthRange glDepthRange;
	OPENGL_FUNC_glDisable glDisable;
	OPENGL_FUNC_glDisableClientState glDisableClientState;
	OPENGL_FUNC_glDrawArrays glDrawArrays;
	OPENGL_FUNC_glDrawBuffer glDrawBuffer;
	OPENGL_FUNC_glDrawElements glDrawElements;
	OPENGL_FUNC_glDrawPixels glDrawPixels;
	OPENGL_FUNC_glEdgeFlag glEdgeFlag;
	OPENGL_FUNC_glEdgeFlagPointer glEdgeFlagPointer;
	OPENGL_FUNC_glEdgeFlagv glEdgeFlagv;
	OPENGL_FUNC_glEnable glEnable;
	OPENGL_FUNC_glEnableClientState glEnableClientState;
	OPENGL_FUNC_glEnd glEnd;
	OPENGL_FUNC_glEndList glEndList;
	OPENGL_FUNC_glEvalCoord1d glEvalCoord1d;
	OPENGL_FUNC_glEvalCoord1dv glEvalCoord1dv;
	OPENGL_FUNC_glEvalCoord1f glEvalCoord1f;
	OPENGL_FUNC_glEvalCoord1fv glEvalCoord1fv;
	OPENGL_FUNC_glEvalCoord2d glEvalCoord2d;
	OPENGL_FUNC_glEvalCoord2dv glEvalCoord2dv;
	OPENGL_FUNC_glEvalCoord2f glEvalCoord2f;
	OPENGL_FUNC_glEvalCoord2fv glEvalCoord2fv;
	OPENGL_FUNC_glEvalMesh1 glEvalMesh1;
	OPENGL_FUNC_glEvalMesh2 glEvalMesh2;
	OPENGL_FUNC_glEvalPoint1 glEvalPoint1;
	OPENGL_FUNC_glEvalPoint2 glEvalPoint2;
	OPENGL_FUNC_glFeedbackBuffer glFeedbackBuffer;
	OPENGL_FUNC_glFinish glFinish;
	OPENGL_FUNC_glFlush glFlush;
	OPENGL_FUNC_glFogf glFogf;
	OPENGL_FUNC_glFogfv glFogfv;
	OPENGL_FUNC_glFogi glFogi;
	OPENGL_FUNC_glFogiv glFogiv;
	OPENGL_FUNC_glFrontFace glFrontFace;
	OPENGL_FUNC_glFrustum glFrustum;
	OPENGL_FUNC_glGenLists glGenLists;
	OPENGL_FUNC_glGenTextures glGenTextures;
	OPENGL_FUNC_glGetBooleanv glGetBooleanv;
	OPENGL_FUNC_glGetClipPlane glGetClipPlane;
	OPENGL_FUNC_glGetDoublev glGetDoublev;
	OPENGL_FUNC_glGetError glGetError;
	OPENGL_FUNC_glGetFloatv glGetFloatv;
	OPENGL_FUNC_glGetIntegerv glGetIntegerv;
	OPENGL_FUNC_glGetLightfv glGetLightfv;
	OPENGL_FUNC_glGetLightiv glGetLightiv;
	OPENGL_FUNC_glGetMapdv glGetMapdv;
	OPENGL_FUNC_glGetMapfv glGetMapfv;
	OPENGL_FUNC_glGetMapiv glGetMapiv;
	OPENGL_FUNC_glGetMaterialfv glGetMaterialfv;
	OPENGL_FUNC_glGetMaterialiv glGetMaterialiv;
	OPENGL_FUNC_glGetPixelMapfv glGetPixelMapfv;
	OPENGL_FUNC_glGetPixelMapuiv glGetPixelMapuiv;
	OPENGL_FUNC_glGetPixelMapusv glGetPixelMapusv;
	OPENGL_FUNC_glGetPointerv glGetPointerv;
	OPENGL_FUNC_glGetPolygonStipple glGetPolygonStipple;
	OPENGL_FUNC_glGetString glGetString;
	OPENGL_FUNC_glGetTexEnvfv glGetTexEnvfv;
	OPENGL_FUNC_glGetTexEnviv glGetTexEnviv;
	OPENGL_FUNC_glGetTexGendv glGetTexGendv;
	OPENGL_FUNC_glGetTexGenfv glGetTexGenfv;
	OPENGL_FUNC_glGetTexGeniv glGetTexGeniv;
	OPENGL_FUNC_glGetTexImage glGetTexImage;
	OPENGL_FUNC_glGetTexLevelParameterfv glGetTexLevelParameterfv;
	OPENGL_FUNC_glGetTexLevelParameteriv glGetTexLevelParameteriv;
	OPENGL_FUNC_glGetTexParameterfv glGetTexParameterfv;
	OPENGL_FUNC_glGetTexParameteriv glGetTexParameteriv;
	OPENGL_FUNC_glHint glHint;
	OPENGL_FUNC_glIndexMask glIndexMask;
	OPENGL_FUNC_glIndexPointer glIndexPointer;
	OPENGL_FUNC_glIndexd glIndexd;
	OPENGL_FUNC_glIndexdv glIndexdv;
	OPENGL_FUNC_glIndexf glIndexf;
	OPENGL_FUNC_glIndexfv glIndexfv;
	OPENGL_FUNC_glIndexi glIndexi;
	OPENGL_FUNC_glIndexiv glIndexiv;
	OPENGL_FUNC_glIndexs glIndexs;
	OPENGL_FUNC_glIndexsv glIndexsv;
	OPENGL_FUNC_glIndexub glIndexub;
	OPENGL_FUNC_glIndexubv glIndexubv;
	OPENGL_FUNC_glInitNames glInitNames;
	OPENGL_FUNC_glInterleavedArrays glInterleavedArrays;
	OPENGL_FUNC_glIsEnabled glIsEnabled;
	OPENGL_FUNC_glIsList glIsList;
	OPENGL_FUNC_glIsTexture glIsTexture;
	OPENGL_FUNC_glLightModelf glLightModelf;
	OPENGL_FUNC_glLightModelfv glLightModelfv;
	OPENGL_FUNC_glLightModeli glLightModeli;
	OPENGL_FUNC_glLightModeliv glLightModeliv;
	OPENGL_FUNC_glLightf glLightf;
	OPENGL_FUNC_glLightfv glLightfv;
	OPENGL_FUNC_glLighti glLighti;
	OPENGL_FUNC_glLightiv glLightiv;
	OPENGL_FUNC_glLineStipple glLineStipple;
	OPENGL_FUNC_glLineWidth glLineWidth;
	OPENGL_FUNC_glListBase glListBase;
	OPENGL_FUNC_glLoadIdentity glLoadIdentity;
	OPENGL_FUNC_glLoadMatrixd glLoadMatrixd;
	OPENGL_FUNC_glLoadMatrixf glLoadMatrixf;
	OPENGL_FUNC_glLoadName glLoadName;
	OPENGL_FUNC_glLogicOp glLogicOp;
	OPENGL_FUNC_glMap1d glMap1d;
	OPENGL_FUNC_glMap1f glMap1f;
	OPENGL_FUNC_glMap2d glMap2d;
	OPENGL_FUNC_glMap2f glMap2f;
	OPENGL_FUNC_glMapGrid1d glMapGrid1d;
	OPENGL_FUNC_glMapGrid1f glMapGrid1f;
	OPENGL_FUNC_glMapGrid2d glMapGrid2d;
	OPENGL_FUNC_glMapGrid2f glMapGrid2f;
	OPENGL_FUNC_glMaterialf glMaterialf;
	OPENGL_FUNC_glMaterialfv glMaterialfv;
	OPENGL_FUNC_glMateriali glMateriali;
	OPENGL_FUNC_glMaterialiv glMaterialiv;
	OPENGL_FUNC_glMatrixMode glMatrixMode;
	OPENGL_FUNC_glMultMatrixd glMultMatrixd;
	OPENGL_FUNC_glMultMatrixf glMultMatrixf;
	OPENGL_FUNC_glNewList glNewList;
	OPENGL_FUNC_glNormal3b glNormal3b;
	OPENGL_FUNC_glNormal3bv glNormal3bv;
	OPENGL_FUNC_glNormal3d glNormal3d;
	OPENGL_FUNC_glNormal3dv glNormal3dv;
	OPENGL_FUNC_glNormal3f glNormal3f;
	OPENGL_FUNC_glNormal3fv glNormal3fv;
	OPENGL_FUNC_glNormal3i glNormal3i;
	OPENGL_FUNC_glNormal3iv glNormal3iv;
	OPENGL_FUNC_glNormal3s glNormal3s;
	OPENGL_FUNC_glNormal3sv glNormal3sv;
	OPENGL_FUNC_glNormalPointer glNormalPointer;
	OPENGL_FUNC_glOrtho glOrtho;
	OPENGL_FUNC_glPassThrough glPassThrough;
	OPENGL_FUNC_glPixelMapfv glPixelMapfv;
	OPENGL_FUNC_glPixelMapuiv glPixelMapuiv;
	OPENGL_FUNC_glPixelMapusv glPixelMapusv;
	OPENGL_FUNC_glPixelStoref glPixelStoref;
	OPENGL_FUNC_glPixelStorei glPixelStorei;
	OPENGL_FUNC_glPixelTransferf glPixelTransferf;
	OPENGL_FUNC_glPixelTransferi glPixelTransferi;
	OPENGL_FUNC_glPixelZoom glPixelZoom;
	OPENGL_FUNC_glPointSize glPointSize;
	OPENGL_FUNC_glPolygonMode glPolygonMode;
	OPENGL_FUNC_glPolygonOffset glPolygonOffset;
	OPENGL_FUNC_glPolygonStipple glPolygonStipple;
	OPENGL_FUNC_glPopAttrib glPopAttrib;
	OPENGL_FUNC_glPopClientAttrib glPopClientAttrib;
	OPENGL_FUNC_glPopMatrix glPopMatrix;
	OPENGL_FUNC_glPopName glPopName;
	OPENGL_FUNC_glPrioritizeTextures glPrioritizeTextures;
	OPENGL_FUNC_glPushAttrib glPushAttrib;
	OPENGL_FUNC_glPushClientAttrib glPushClientAttrib;
	OPENGL_FUNC_glPushMatrix glPushMatrix;
	OPENGL_FUNC_glPushName glPushName;
	OPENGL_FUNC_glRasterPos2d glRasterPos2d;
	OPENGL_FUNC_glRasterPos2dv glRasterPos2dv;
	OPENGL_FUNC_glRasterPos2f glRasterPos2f;
	OPENGL_FUNC_glRasterPos2fv glRasterPos2fv;
	OPENGL_FUNC_glRasterPos2i glRasterPos2i;
	OPENGL_FUNC_glRasterPos2iv glRasterPos2iv;
	OPENGL_FUNC_glRasterPos2s glRasterPos2s;
	OPENGL_FUNC_glRasterPos2sv glRasterPos2sv;
	OPENGL_FUNC_glRasterPos3d glRasterPos3d;
	OPENGL_FUNC_glRasterPos3dv glRasterPos3dv;
	OPENGL_FUNC_glRasterPos3f glRasterPos3f;
	OPENGL_FUNC_glRasterPos3fv glRasterPos3fv;
	OPENGL_FUNC_glRasterPos3i glRasterPos3i;
	OPENGL_FUNC_glRasterPos3iv glRasterPos3iv;
	OPENGL_FUNC_glRasterPos3s glRasterPos3s;
	OPENGL_FUNC_glRasterPos3sv glRasterPos3sv;
	OPENGL_FUNC_glRasterPos4d glRasterPos4d;
	OPENGL_FUNC_glRasterPos4dv glRasterPos4dv;
	OPENGL_FUNC_glRasterPos4f glRasterPos4f;
	OPENGL_FUNC_glRasterPos4fv glRasterPos4fv;
	OPENGL_FUNC_glRasterPos4i glRasterPos4i;
	OPENGL_FUNC_glRasterPos4iv glRasterPos4iv;
	OPENGL_FUNC_glRasterPos4s glRasterPos4s;
	OPENGL_FUNC_glRasterPos4sv glRasterPos4sv;
	OPENGL_FUNC_glReadBuffer glReadBuffer;
	OPENGL_FUNC_glReadPixels glReadPixels;
	OPENGL_FUNC_glRectd glRectd;
	OPENGL_FUNC_glRectdv glRectdv;
	OPENGL_FUNC_glRectf glRectf;
	OPENGL_FUNC_glRectfv glRectfv;
	OPENGL_FUNC_glRecti glRecti;
	OPENGL_FUNC_glRectiv glRectiv;
	OPENGL_FUNC_glRects glRects;
	OPENGL_FUNC_glRectsv glRectsv;
	OPENGL_FUNC_glRenderMode glRenderMode;
	OPENGL_FUNC_glRotated glRotated;
	OPENGL_FUNC_glRotatef glRotatef;
	OPENGL_FUNC_glScaled glScaled;
	OPENGL_FUNC_glScalef glScalef;
	OPENGL_FUNC_glScissor glScissor;
	OPENGL_FUNC_glSelectBuffer glSelectBuffer;
	OPENGL_FUNC_glShadeModel glShadeModel;
	OPENGL_FUNC_glStencilFunc glStencilFunc;
	OPENGL_FUNC_glStencilMask glStencilMask;
	OPENGL_FUNC_glStencilOp glStencilOp;
	OPENGL_FUNC_glTexCoord1d glTexCoord1d;
	OPENGL_FUNC_glTexCoord1dv glTexCoord1dv;
	OPENGL_FUNC_glTexCoord1f glTexCoord1f;
	OPENGL_FUNC_glTexCoord1fv glTexCoord1fv;
	OPENGL_FUNC_glTexCoord1i glTexCoord1i;
	OPENGL_FUNC_glTexCoord1iv glTexCoord1iv;
	OPENGL_FUNC_glTexCoord1s glTexCoord1s;
	OPENGL_FUNC_glTexCoord1sv glTexCoord1sv;
	OPENGL_FUNC_glTexCoord2d glTexCoord2d;
	OPENGL_FUNC_glTexCoord2dv glTexCoord2dv;
	OPENGL_FUNC_glTexCoord2f glTexCoord2f;
	OPENGL_FUNC_glTexCoord2fv glTexCoord2fv;
	OPENGL_FUNC_glTexCoord2i glTexCoord2i;
	OPENGL_FUNC_glTexCoord2iv glTexCoord2iv;
	OPENGL_FUNC_glTexCoord2s glTexCoord2s;
	OPENGL_FUNC_glTexCoord2sv glTexCoord2sv;
	OPENGL_FUNC_glTexCoord3d glTexCoord3d;
	OPENGL_FUNC_glTexCoord3dv glTexCoord3dv;
	OPENGL_FUNC_glTexCoord3f glTexCoord3f;
	OPENGL_FUNC_glTexCoord3fv glTexCoord3fv;
	OPENGL_FUNC_glTexCoord3i glTexCoord3i;
	OPENGL_FUNC_glTexCoord3iv glTexCoord3iv;
	OPENGL_FUNC_glTexCoord3s glTexCoord3s;
	OPENGL_FUNC_glTexCoord3sv glTexCoord3sv;
	OPENGL_FUNC_glTexCoord4d glTexCoord4d;
	OPENGL_FUNC_glTexCoord4dv glTexCoord4dv;
	OPENGL_FUNC_glTexCoord4f glTexCoord4f;
	OPENGL_FUNC_glTexCoord4fv glTexCoord4fv;
	OPENGL_FUNC_glTexCoord4i glTexCoord4i;
	OPENGL_FUNC_glTexCoord4iv glTexCoord4iv;
	OPENGL_FUNC_glTexCoord4s glTexCoord4s;
	OPENGL_FUNC_glTexCoord4sv glTexCoord4sv;
	OPENGL_FUNC_glTexCoordPointer glTexCoordPointer;
	OPENGL_FUNC_glTexEnvf glTexEnvf;
	OPENGL_FUNC_glTexEnvfv glTexEnvfv;
	OPENGL_FUNC_glTexEnvi glTexEnvi;
	OPENGL_FUNC_glTexEnviv glTexEnviv;
	OPENGL_FUNC_glTexGend glTexGend;
	OPENGL_FUNC_glTexGendv glTexGendv;
	OPENGL_FUNC_glTexGenf glTexGenf;
	OPENGL_FUNC_glTexGenfv glTexGenfv;
	OPENGL_FUNC_glTexGeni glTexGeni;
	OPENGL_FUNC_glTexGeniv glTexGeniv;
	OPENGL_FUNC_glTexImage1D glTexImage1D;
	OPENGL_FUNC_glTexImage2D glTexImage2D;
	OPENGL_FUNC_glTexParameterf glTexParameterf;
	OPENGL_FUNC_glTexParameterfv glTexParameterfv;
	OPENGL_FUNC_glTexParameteri glTexParameteri;
	OPENGL_FUNC_glTexParameteriv glTexParameteriv;
	OPENGL_FUNC_glTexSubImage1D glTexSubImage1D;
	OPENGL_FUNC_glTexSubImage2D glTexSubImage2D;
	OPENGL_FUNC_glTranslated glTranslated;
	OPENGL_FUNC_glTranslatef glTranslatef;
	OPENGL_FUNC_glVertex2d glVertex2d;
	OPENGL_FUNC_glVertex2dv glVertex2dv;
	OPENGL_FUNC_glVertex2f glVertex2f;
	OPENGL_FUNC_glVertex2fv glVertex2fv;
	OPENGL_FUNC_glVertex2i glVertex2i;
	OPENGL_FUNC_glVertex2iv glVertex2iv;
	OPENGL_FUNC_glVertex2s glVertex2s;
	OPENGL_FUNC_glVertex2sv glVertex2sv;
	OPENGL_FUNC_glVertex3d glVertex3d;
	OPENGL_FUNC_glVertex3dv glVertex3dv;
	OPENGL_FUNC_glVertex3f glVertex3f;
	OPENGL_FUNC_glVertex3fv glVertex3fv;
	OPENGL_FUNC_glVertex3i glVertex3i;
	OPENGL_FUNC_glVertex3iv glVertex3iv;
	OPENGL_FUNC_glVertex3s glVertex3s;
	OPENGL_FUNC_glVertex3sv glVertex3sv;
	OPENGL_FUNC_glVertex4d glVertex4d;
	OPENGL_FUNC_glVertex4dv glVertex4dv;
	OPENGL_FUNC_glVertex4f glVertex4f;
	OPENGL_FUNC_glVertex4fv glVertex4fv;
	OPENGL_FUNC_glVertex4i glVertex4i;
	OPENGL_FUNC_glVertex4iv glVertex4iv;
	OPENGL_FUNC_glVertex4s glVertex4s;
	OPENGL_FUNC_glVertex4sv glVertex4sv;
	OPENGL_FUNC_glVertexPointer glVertexPointer;
	OPENGL_FUNC_glViewport glViewport;
};

bool LoadContent(OPENGL_CONTEXT & context);
bool Draw(OPENGL_CONTEXT & context);
void UnloadContent(OPENGL_CONTEXT & context);

#endif // OPENGL_MAIN_H
